const titles=['Bìa tập san','Ngôi trường mến mộ','Lời ngỏ','Dấu ấn điện ảnh','Dưới mái trường yêu dấu','Niên khóa 1987–1994','Tri thức và ký ức','Niên khóa 1992–1999','Ký ức tuổi học trò','Niên khóa 1997–2004','Tri ân người khai sáng','Niên khóa 2002–2008','Hành trình trưởng thành','Niên khóa 2006–2012','Người thầy trong tim','Niên khóa 2010–2016','Một chặng đường','Niên khóa 2014–2020','Dấu son truyền thống','Niên khóa 2018–2023','Lời kết'];
const pages=titles.map((title,i)=>({title,src:`assets/pages/page-${String(i+1).padStart(2,'0')}.webp`}));
const $=s=>document.querySelector(s);
const reader=$('#reader'),landing=$('#landing'),book=$('#book'),viewport=$('#bookViewport'),left=$('#leftSlot'),right=$('#rightSlot'),flip=$('#flipSheet');
let current=0,soundOn=true,animating=false,scale=1,panX=0,panY=0,startX=0,startY=0,lastX=0,lastY=0,startDistance=0,startScale=1,panning=false,pinching=false;
const pageHTML=i=>i>=0&&i<pages.length?`<img class="page-image" src="${pages[i].src}" alt="${pages[i].title}, trang ${i+1}">`:'';
function spreadStart(i){if(i<=0)return 0;return i%2===1?i:i-1}
function playFlip(){if(!soundOn)return;try{const C=window.AudioContext||window.webkitAudioContext,a=new C(),o=a.createOscillator(),g=a.createGain();o.type='triangle';o.frequency.setValueAtTime(175,a.currentTime);o.frequency.exponentialRampToValueAtTime(62,a.currentTime+.1);g.gain.setValueAtTime(.035,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.12);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.13)}catch{}}
function updateTransform(){book.style.transform=`translate3d(${panX}px,${panY}px,0) scale(${scale})`;$('#resetZoomBtn').textContent=`${Math.round(scale*100)}%`}
function resetZoom(){scale=1;panX=0;panY=0;updateTransform()}
function render(){const cover=current===0;book.classList.toggle('cover-mode',cover);if(cover){left.innerHTML='';right.innerHTML=pageHTML(0)}else{current=spreadStart(current);left.innerHTML=pageHTML(current);right.innerHTML=pageHTML(current+1)}left.classList.toggle('empty',!left.innerHTML);right.classList.toggle('empty',!right.innerHTML);$('#chapterTitle').textContent=pages[current].title;$('#pageLabel').textContent=cover?`Bìa · Trang 1 / ${pages.length}`:`Trang ${current+1}${current+1<pages.length?'–'+Math.min(current+2,pages.length):''} / ${pages.length}`;$('#pageRange').value=current+1;$('#prevBtn').disabled=current===0;$('#nextBtn').disabled=current>=pages.length-1;document.querySelectorAll('.thumb').forEach((el,i)=>el.classList.toggle('active',i===current||(!cover&&i===current+1)))}
function animateFlip(direction,nextCurrent){if(animating)return;animating=true;const isNext=direction==='next',cover=current===0;if(cover){book.classList.add('opening');setTimeout(()=>{book.classList.remove('opening');current=nextCurrent;render();animating=false},420);return}const frontIndex=isNext?current+1:current,backIndex=isNext?Math.min(current+2,pages.length-1):Math.max(0,current-1);flip.className=`flip-sheet active ${direction}`;flip.querySelector('.flip-front').style.backgroundImage=`url('${pages[frontIndex]?.src||''}')`;flip.querySelector('.flip-back').style.backgroundImage=`url('${pages[backIndex]?.src||''}')`;setTimeout(()=>{current=nextCurrent;render()},350);setTimeout(()=>{flip.className='flip-sheet';animating=false},720)}
function go(delta){if(animating)return;const step=current===0?1:2;let next=current+delta*step;if(delta<0&&current===1)next=0;next=Math.max(0,Math.min(pages.length-1,next));next=spreadStart(next);if(next===current)return;resetZoom();playFlip();animateFlip(delta>0?'next':'prev',next)}
function openReader(){landing.hidden=true;reader.hidden=false;document.body.classList.add('reading');current=Number(localStorage.getItem('tapSanPage')||0);if(current<0||current>=pages.length)current=0;resetZoom();render()}
function closeReader(){localStorage.setItem('tapSanPage',String(current));reader.hidden=true;landing.hidden=false;document.body.classList.remove('reading');resetZoom()}
$('#openBookBtn').onclick=openReader;$('#closeReaderBtn').onclick=closeReader;$('#homeLink').onclick=e=>{e.preventDefault();closeReader()};$('#nextBtn').onclick=()=>go(1);$('#prevBtn').onclick=()=>go(-1);$('#resetZoomBtn').onclick=resetZoom;
$('#pageRange').onchange=e=>{const target=spreadStart(Number(e.target.value)-1);if(target===current)return;const dir=target>current?'next':'prev';resetZoom();playFlip();animateFlip(dir,target)};
$('#soundBtn').onclick=e=>{soundOn=!soundOn;e.currentTarget.textContent=soundOn?'🔊':'🔇'};$('#fullscreenBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.();
const panel=$('#thumbPanel'),overlay=$('#overlay');function panelOpen(v){panel.classList.toggle('open',v);panel.setAttribute('aria-hidden',String(!v));overlay.hidden=!v}$('#thumbBtn').onclick=()=>panelOpen(true);$('#closeThumbBtn').onclick=()=>panelOpen(false);overlay.onclick=()=>panelOpen(false);
const grid=$('#thumbGrid');pages.forEach((p,i)=>{const b=document.createElement('button');b.className='thumb';b.innerHTML=`<img loading="lazy" src="${p.src}" alt="${p.title}"><span>${i+1}</span>`;b.onclick=()=>{const target=spreadStart(i);current=target;resetZoom();render();panelOpen(false)};grid.appendChild(b)});
function distance(t){return Math.hypot(t[0].clientX-t[1].clientX,t[0].clientY-t[1].clientY)}
viewport.addEventListener('touchstart',e=>{if(e.touches.length===2){pinching=true;panning=false;startDistance=distance(e.touches);startScale=scale}else if(e.touches.length===1){startX=lastX=e.touches[0].clientX;startY=lastY=e.touches[0].clientY;panning=scale>1}}, {passive:false});
viewport.addEventListener('touchmove',e=>{if(e.touches.length===2){e.preventDefault();pinching=true;scale=Math.max(1,Math.min(4,startScale*distance(e.touches)/startDistance));updateTransform()}else if(e.touches.length===1&&scale>1){e.preventDefault();const x=e.touches[0].clientX,y=e.touches[0].clientY;panX+=x-lastX;panY+=y-lastY;lastX=x;lastY=y;updateTransform()}},{passive:false});
viewport.addEventListener('touchend',e=>{if(pinching){pinching=false;if(scale<1.05)resetZoom();return}if(e.changedTouches.length&&scale===1){const dx=e.changedTouches[0].clientX-startX,dy=e.changedTouches[0].clientY-startY;if(Math.abs(dx)>48&&Math.abs(dx)>Math.abs(dy)*1.2)go(dx<0?1:-1)}panning=false},{passive:true});
viewport.addEventListener('wheel',e=>{if(!e.ctrlKey)return;e.preventDefault();scale=Math.max(1,Math.min(4,scale+(e.deltaY<0?.15:-.15)));updateTransform()},{passive:false});
addEventListener('keydown',e=>{if(reader.hidden)return;if(e.key==='ArrowRight')go(1);if(e.key==='ArrowLeft')go(-1);if(e.key==='Escape'){if(panel.classList.contains('open'))panelOpen(false);else closeReader()}});addEventListener('beforeunload',()=>localStorage.setItem('tapSanPage',String(current)));
render();
